blank_issues_enabled: false
contact_links:
  - name: Looking to give feedback on PowerShell?
    url: https://github.com/PowerShell/PowerShell/issues/new/choose
    about: Please open feature requests for current PowerShell here.
  - name: Looking to give feedback on DSC?
    url: https://github.com/PowerShell/PSDesiredStateConfiguration/issues/new/choose
    about: Please open feature requests for DSC here.
  - name: Looking for support?
    url: https://dsccommunity.org/help/
    about: DSC support resources
  - name: What's the Quality Contributions Project?
      url: https://learn.microsoft.com/powershell/scripting/community/contributing/quality-improvements
      about: >-
        If you'd like to commit to improving quality for the documentation, before filing an issue,
        check the info and instructions.
